[package]
name = "api"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13.4"
prost-types = "0.13.4"
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"

[env]
OUT_DIR = "target"
