[package]
name = "api"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13.4"
prost-types = "0.13.4"
tokio = {version="1.43.0", features=["rt-multi-thread"]}
tonic = "0.12.3"
database_api = { path = "../database_api" }

[build-dependencies]
tonic-build = "0.12.3"
